project:
  type: website
  output-dir: docs
  
website:
  title: "Andrew's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: dark
    css: styles.css
    toc: true

editor: visual

