---
title: About
---

My name is Andrew Zimbelman. I am a 4th year Ecosystem Science & Sustainability major who is interested in regenerative agriculture, sustainable urban development, conservation, and environmental justice. In my career I am driven to finding ways to connect our agricultural system to underprivileged urban communities that are victims to policies that have created food deserts. I am confident my work will provide nutritious, affordable, healthy food to under supported regions of Colorado! I also aim to ensure that our natural areas are preserved for future generations. 

```         
```

---
tite: "Leadership and Environmental Experience"
---

I have held various positions over the course of my career, I have worked in a variety of places from fast food to out on farms. My most significant work experience has come from my time in high school to now. ,where I first started working as a carryout at my local nursery Echter's. Being a carryout demanded that I have knowledge over various types of plant's as well as the knowledge to properly identify and recommend various types of mulch, compost, and soil types.

My previous internship experiences have consisted of working at a wetland restoration company called Westervelt, and 2 farms; Growing Gardens in Boulder, and Expanding Horizons in Fort Collins 

At Westervelt Ecological Services in Golden, I served as a ecological stewardship intern. In this position, I assisted with field work data collection and site maintenance in various cities in states. This data was used to help make reports and advance through phases of restoration projects. In this position, I used various softwares, such as ArcGIS, Fieldmaps, Excel, Microsoft Teams, and more. I also collected field data through delineations, topographic surveys, and vegetation assessments 

My farming experience has consisted of asssiting with vegetable harvesting and planting, as well as bed flipping, setting up irrigation, and weed control & maintenance. I have also done soil testing and farm soil assessments in order to make personalized plans for sustainable agriculture practices. 

My outdoor's experience does not end here. I have also volunteered for the Wildland Restoration volutneer group. My Volunteer work with this group has focused on 2 significant projects. The first project focuses on planting cover crops for a local farm in Longmont to ensure a more sustainable farming ecosystem was able to persist in various Colorado climates, we did so by planting crops that were designed to protect against wind shearing by digging holes that were around 1-2 feet into the ground, we then gently broke up the plant soil, ensuring there was a higher surface area for root movement to increase land coverage and decrease root competiton, we then placed a layer of mycelia on top of the plants, and then a layer of dirt on top to protect the mycelia from the potential damage from the sun. On top of this, we also worked on creating a beautiful pollinator garden to support a more natural & sustainable farm ecosystem. The second volunteer project focused on ecosystem restoration in an outdoors area in Loveland. In this project, we removed pests, weeds, and dead plants to plant fresh soil with early succesional plant species that would help to restore the ecosytem. We did this the use of various tools such as shovels and pickaxes to remove rock and make room for new plants and soil, which we planted deep in the soil to ensure that their roots could grow into the neighboring soil, allowing them to properly establish and grow.

My most recent experience has been at Colorado State Universities largest dining hall known as, "Ram's Horn". At Ram's Horn I am one of the Student Managers. My job is to ensure that all employees documentation and scheduling is completed as well as training all employees and supervisors. I also am responsible for ensuring that the dining hall follows state mandated food safety regulations as well as labor laws. 
